"use client";

import { motion } from "framer-motion";
import Link from "next/link";

export default function StatementOfFaith() {
  return (
    <div className="w-full relative overflow-hidden flex flex-col items-center pt-32 pb-20">
      <div className="fixed top-[-20%] right-[-10%] w-[500px] h-[500px] bg-brand-gold/10 rounded-full blur-[120px] pointer-events-none" />

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full max-w-4xl mx-auto px-6"
      >
        <h1 className="text-3xl lg:text-4xl font-serif mb-10 text-[#5b5b42] uppercase tracking-wide text-center">
          Statement of Faith
        </h1>

        <ol className="list-decimal list-outside pl-6 space-y-6 text-[#5b5b42] text-[17px] leading-relaxed font-serif max-w-3xl mx-auto">
          <li>We believe in one God, Creator of all things, infinitely perfect and eternally existing in three persons: Father, Son and Holy Spirit.</li>
          <li>We believe the Bible to be the inspired, authoritative Word of God, infallible and inerrant in its original writings. It is the complete revelation of His will for the salvation of men and the divine and final authority for all Christian faith and life.</li>
          <li>We believe that Jesus Christ is true God and true man, having been conceived of the Holy Spirit and born of the Virgin Mary. We believe in His sinless life, in His miracles, in His vicarious and atoning death through His shed blood, in His bodily resurrection, in His ascension to the right hand of the Father and in His personal return as King of Kings and Lord of Lords.</li>
          <li>We believe that man was created in the image of God but fell into sin and is therefore lost and out of God&apos;s abundant love. Through regeneration by the Holy Spirit he can obtain salvation and eternal life. This salvation is by grace alone through the shed blood of Jesus Christ, the Son of God.</li>
          <li>We believe in the present ministry of the Holy Spirit by whose indwelling the Christian is enabled to live a godly life.</li>
          <li>We believe that Jesus Christ is the Lord and the Head of the Church, and that every local Church has the right under Christ to decide and govern its own affairs.</li>
          <li>We believe that the true Church is composed of all such persons who through saving faith in Jesus Christ have been regenerated by the Holy Spirit and are united together in the body of Christ of which He is the head.</li>
        </ol>

        <div className="flex gap-4 justify-center mt-12">
          <Link href="/" className="bg-brand-gold hover:brightness-90 text-white px-7 py-2.5 rounded-full text-sm font-sans transition-all tracking-wide shadow-md">
            Back to Home
          </Link>
          <Link href="/mission-statement" className="bg-brand-gold hover:brightness-90 text-white px-7 py-2.5 rounded-full text-sm font-sans transition-all tracking-wide shadow-md">
            ← Mission Statement
          </Link>
        </div>
      </motion.div>
    </div>
  );
}
